Replaces WinSCP with SSH.NET for SFTP downloads
amanaconsulting/ifp-client pull request #20
Opened 2018-09-18 14:19 UTC by chris-behle

WinSCP has a quite large footprint and also integrates as a project
item in consuming libraries. As a result a .gitignore rule has to
be written. The SSH.NET library seems to be a good alternative.

The code is untestet, due to the lack of credentials.

2018-09-18 18:54 UTC, richieeeeeeee commented
Looks good!

2018-09-19 08:32 UTC, dpa-amana requested changes

2018-09-19 08:32 UTC, dpa-amana commented on AMANA.IFP.Common/Helpers/RoutingTableReader.cs
> +                    client.DownloadFile(remoteFilePath, new FileStream(localSaveFilePath, FileMode.Create));
Hier wird ein FileStream erzeugt. Dieser wird jedoch nicht geschlossen, sodass es zu einer Exception kommt, sobald später versucht wird, auf die Datei zuzugreifen. Daher würde ich ein using für den Stream erstellen, um sicherzustellen, dass dieser geschlossen und disposed wird, sobald die Datei heruntergeladen wurde.

2018-09-19 08:45 UTC, chris-behle commented on AMANA.IFP.Common/Helpers/RoutingTableReader.cs
> +                    client.DownloadFile(remoteFilePath, new FileStream(localSaveFilePath, FileMode.Create));
See bb0d438

2018-09-19 09:10 UTC, merged